.PHONY: all c1 c2 c3 r2 r3

all: c1 c2 c3 r2 r3

c1:
	cat c1.txt | ./hex2raw | ./ctarget -q

c2:
	cat c2.txt | ./hex2raw | ./ctarget -q

c3:
	cat c3.txt | ./hex2raw | ./ctarget -q

r2:
	cat r2.txt | ./hex2raw | ./rtarget -q

r3:
	cat r3.txt | ./hex2raw | ./rtarget -q
